/**
 * @file v_pace_db.h
 *
 * @brief This header file was generated by cantools version 42.0.1 Thu Jun 25 16:16:23 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef V_PACE_DB_H
#define V_PACE_DB_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define V_PACE_DB_ENCODER_DATA_FRAME_ID (0x100u)
#define V_PACE_DB_IMU_ACCEL_FRAME_ID (0x101u)
#define V_PACE_DB_IMU_GYRO_FLAGS_FRAME_ID (0x102u)
#define V_PACE_DB_MOTOR_COMMANDS_FRAME_ID (0x200u)
#define V_PACE_DB_STEERING_COMMAND_FRAME_ID (0x201u)
#define V_PACE_DB_RESET_COMMAND_FRAME_ID (0x202u)

/* Frame lengths in bytes. */
#define V_PACE_DB_ENCODER_DATA_LENGTH (8u)
#define V_PACE_DB_IMU_ACCEL_LENGTH (8u)
#define V_PACE_DB_IMU_GYRO_FLAGS_LENGTH (8u)
#define V_PACE_DB_MOTOR_COMMANDS_LENGTH (8u)
#define V_PACE_DB_STEERING_COMMAND_LENGTH (4u)
#define V_PACE_DB_RESET_COMMAND_LENGTH (1u)

/* Extended or standard frame types. */
#define V_PACE_DB_ENCODER_DATA_IS_EXTENDED (0)
#define V_PACE_DB_IMU_ACCEL_IS_EXTENDED (0)
#define V_PACE_DB_IMU_GYRO_FLAGS_IS_EXTENDED (0)
#define V_PACE_DB_MOTOR_COMMANDS_IS_EXTENDED (0)
#define V_PACE_DB_STEERING_COMMAND_IS_EXTENDED (0)
#define V_PACE_DB_RESET_COMMAND_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define V_PACE_DB_ENCODER_DATA_NAME "EncoderData"
#define V_PACE_DB_IMU_ACCEL_NAME "ImuAccel"
#define V_PACE_DB_IMU_GYRO_FLAGS_NAME "ImuGyroFlags"
#define V_PACE_DB_MOTOR_COMMANDS_NAME "MotorCommands"
#define V_PACE_DB_STEERING_COMMAND_NAME "SteeringCommand"
#define V_PACE_DB_RESET_COMMAND_NAME "ResetCommand"

/* Signal Names. */
#define V_PACE_DB_ENCODER_DATA_LEFT_TICKS_NAME "LeftTicks"
#define V_PACE_DB_ENCODER_DATA_RIGHT_TICKS_NAME "RightTicks"
#define V_PACE_DB_IMU_ACCEL_ACCEL_X_NAME "AccelX"
#define V_PACE_DB_IMU_ACCEL_ACCEL_Y_NAME "AccelY"
#define V_PACE_DB_IMU_ACCEL_ACCEL_Z_NAME "AccelZ"
#define V_PACE_DB_IMU_ACCEL_SEQUENCE_NAME "Sequence"
#define V_PACE_DB_IMU_ACCEL_RESERVED_NAME "Reserved"
#define V_PACE_DB_IMU_GYRO_FLAGS_GYRO_X_NAME "GyroX"
#define V_PACE_DB_IMU_GYRO_FLAGS_GYRO_Y_NAME "GyroY"
#define V_PACE_DB_IMU_GYRO_FLAGS_GYRO_Z_NAME "GyroZ"
#define V_PACE_DB_IMU_GYRO_FLAGS_IMU_RESET_NAME "ImuReset"
#define V_PACE_DB_IMU_GYRO_FLAGS_SEQUENCE_NAME "Sequence"
#define V_PACE_DB_MOTOR_COMMANDS_LEFT_VEL_NAME "LeftVel"
#define V_PACE_DB_MOTOR_COMMANDS_RIGHT_VEL_NAME "RightVel"
#define V_PACE_DB_STEERING_COMMAND_STEER_ANGLE_NAME "SteerAngle"
#define V_PACE_DB_RESET_COMMAND_RESET_NAME "Reset"

/**
 * Signals in message EncoderData.
 *
 * Encoder tick counts from quadrature encoders on drive wheels. Cumulative, wraps at int32 limits.
 *
 * All signal values are as on the CAN bus.
 */
struct v_pace_db_encoder_data_t {
    /**
     * Range: -2147483648..2147483647 (-2147483648..2147483647 ticks)
     * Scale: 1
     * Offset: 0
     */
    int32_t left_ticks;

    /**
     * Range: -2147483648..2147483647 (-2147483648..2147483647 ticks)
     * Scale: 1
     * Offset: 0
     */
    int32_t right_ticks;
};

/**
 * Signals in message ImuAccel.
 *
 * Accelerometer X/Y/Z with sequence counter for frame synchronization. Scale 0.001: 1 LSB = 0.001 m/s^2. IMU configured to +/-2g accel.
 *
 * All signal values are as on the CAN bus.
 */
struct v_pace_db_imu_accel_t {
    /**
     * Range: -32768..32767 (-32.768..32.767 m/s^2)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t accel_x;

    /**
     * Range: -32768..32767 (-32.768..32.767 m/s^2)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t accel_y;

    /**
     * Range: -32768..32767 (-32.768..32.767 m/s^2)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t accel_z;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t sequence;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t reserved;
};

/**
 * Signals in message ImuGyroFlags.
 *
 * Gyroscope X/Y/Z axes, IMU reset flag, and sequence counter. GyroZ is pre-inverted by TivaC to match robot frame. Scale 0.001.
 *
 * All signal values are as on the CAN bus.
 */
struct v_pace_db_imu_gyro_flags_t {
    /**
     * Range: -32768..32767 (-32.768..32.767 rad/s)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t gyro_x;

    /**
     * Range: -32768..32767 (-32.768..32.767 rad/s)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t gyro_y;

    /**
     * Range: -32768..32767 (-32.768..32.767 rad/s)
     * Scale: 0.001
     * Offset: 0
     */
    int16_t gyro_z;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t imu_reset;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t sequence;
};

/**
 * Signals in message MotorCommands.
 *
 * Motor velocity commands in rad/s. IEEE 754 float32 encoding.
 *
 * All signal values are as on the CAN bus.
 */
struct v_pace_db_motor_commands_t {
    /**
     * Range: -3.4e+38..3.4e+38 (-3.4e+38..3.4e+38 rad/s)
     * Scale: 1
     * Offset: 0
     */
    float left_vel;

    /**
     * Range: -3.4e+38..3.4e+38 (-3.4e+38..3.4e+38 rad/s)
     * Scale: 1
     * Offset: 0
     */
    float right_vel;
};

/**
 * Signals in message SteeringCommand.
 *
 * Steering angle command in radians. TivaC converts to servo PWM locally.
 *
 * All signal values are as on the CAN bus.
 */
struct v_pace_db_steering_command_t {
    /**
     * Range: -3.4e+38..3.4e+38 (-3.4e+38..3.4e+38 rad)
     * Scale: 1
     * Offset: 0
     */
    float steer_angle;
};

/**
 * Signals in message ResetCommand.
 *
 * Hardware reset command. Set Reset=1 to trigger encoder zero and IMU re-init.
 *
 * All signal values are as on the CAN bus.
 */
struct v_pace_db_reset_command_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t reset;
};

/**
 * Unpack message EncoderData.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int v_pace_db_encoder_data_unpack(
    struct v_pace_db_encoder_data_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EncoderData.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int v_pace_db_encoder_data_init(struct v_pace_db_encoder_data_t *msg_p);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_encoder_data_left_ticks_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_encoder_data_left_ticks_is_in_range(int32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_encoder_data_left_ticks_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_encoder_data_right_ticks_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_encoder_data_right_ticks_is_in_range(int32_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_encoder_data_right_ticks_is_in_phys_range(float value);

/**
 * Unpack message ImuAccel.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int v_pace_db_imu_accel_unpack(
    struct v_pace_db_imu_accel_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ImuAccel.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int v_pace_db_imu_accel_init(struct v_pace_db_imu_accel_t *msg_p);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_imu_accel_accel_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_accel_accel_x_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_accel_accel_x_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_imu_accel_accel_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_accel_accel_y_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_accel_accel_y_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_imu_accel_accel_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_accel_accel_z_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_accel_accel_z_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_imu_accel_sequence_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_accel_sequence_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_accel_sequence_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_imu_accel_reserved_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_accel_reserved_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_accel_reserved_is_in_phys_range(float value);

/**
 * Unpack message ImuGyroFlags.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int v_pace_db_imu_gyro_flags_unpack(
    struct v_pace_db_imu_gyro_flags_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ImuGyroFlags.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int v_pace_db_imu_gyro_flags_init(struct v_pace_db_imu_gyro_flags_t *msg_p);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_imu_gyro_flags_gyro_x_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_gyro_flags_gyro_x_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_gyro_flags_gyro_x_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_imu_gyro_flags_gyro_y_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_gyro_flags_gyro_y_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_gyro_flags_gyro_y_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_imu_gyro_flags_gyro_z_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_gyro_flags_gyro_z_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_gyro_flags_gyro_z_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_imu_gyro_flags_imu_reset_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_gyro_flags_imu_reset_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_gyro_flags_imu_reset_is_in_phys_range(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float v_pace_db_imu_gyro_flags_sequence_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_gyro_flags_sequence_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_imu_gyro_flags_sequence_is_in_phys_range(float value);

/**
 * Pack message MotorCommands.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int v_pace_db_motor_commands_pack(
    uint8_t *dst_p,
    const struct v_pace_db_motor_commands_t *src_p,
    size_t size);

/**
 * Init message fields to default values from MotorCommands.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int v_pace_db_motor_commands_init(struct v_pace_db_motor_commands_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float v_pace_db_motor_commands_left_vel_encode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_motor_commands_left_vel_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_motor_commands_left_vel_is_in_phys_range(float value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float v_pace_db_motor_commands_right_vel_encode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_motor_commands_right_vel_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_motor_commands_right_vel_is_in_phys_range(float value);

/**
 * Pack message SteeringCommand.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int v_pace_db_steering_command_pack(
    uint8_t *dst_p,
    const struct v_pace_db_steering_command_t *src_p,
    size_t size);

/**
 * Init message fields to default values from SteeringCommand.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int v_pace_db_steering_command_init(struct v_pace_db_steering_command_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
float v_pace_db_steering_command_steer_angle_encode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_steering_command_steer_angle_is_in_range(float value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_steering_command_steer_angle_is_in_phys_range(float value);

/**
 * Pack message ResetCommand.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int v_pace_db_reset_command_pack(
    uint8_t *dst_p,
    const struct v_pace_db_reset_command_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ResetCommand.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int v_pace_db_reset_command_init(struct v_pace_db_reset_command_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t v_pace_db_reset_command_reset_encode(float value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_reset_command_reset_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool v_pace_db_reset_command_reset_is_in_phys_range(float value);


#ifdef __cplusplus
}
#endif

#endif
