SUMMARY = "IVI OTA agent (MQTT campaign -> download -> decrypt -> swupdate)"
DESCRIPTION = "Subscribes to an Adafruit IO feed, validates the campaign, downloads \
the encrypted .swu from Backblaze B2, RSA-unwraps the AES session key, decrypts, \
and hands the package to swupdate."
LICENSE = "CLOSED"

SRC_URI = "file://ivi_ota_agent.sh \
           file://ivi-ota-agent.service \
           file://ota-approval-tmpfiles.conf"

S = "${WORKDIR}"

# VPACE_OTA_VERSION -- the single OTA counter, shared with ivi-update and
# ackermann-update. do_install generates the agent's INITIAL_VERSION floor from
# it; see the include for why the floor must track the image.
require conf/include/vpace-ota-version.inc

inherit systemd

SYSTEMD_SERVICE:${PN} = "ivi-ota-agent.service"
SYSTEMD_AUTO_ENABLE = "enable"

PACKAGECONFIG ??= ""
PACKAGECONFIG[ros2-coordination] = ",,,ros2cli update-coordinator"

# mosquitto-clients -> mosquitto_sub / mosquitto_pub
# curl              -> the download
# openssl           -> RSA unwrap + AES decrypt + base64 (the agent uses
#                      `openssl base64`, NOT coreutils, so coreutils is NOT needed)
# swupdate          -> the actual install
# cpio              -> the .swu magic sanity check
RDEPENDS:${PN} = "mosquitto-clients curl openssl swupdate cpio"

# The installed-version file lives at /data/ota/installed_version, and the
# directory is created at boot by mount-data-partition.sh -- /data is a mount
# point, so nothing staged into it at image build time would ever be visible.
RDEPENDS:${PN} += "data-partition-mount"

do_install() {
    install -d ${D}${bindir}
    install -m 0755 ${WORKDIR}/ivi_ota_agent.sh ${D}${bindir}/ivi_ota_agent.sh

    install -d ${D}${systemd_system_unitdir}
    install -m 0644 ${WORKDIR}/ivi-ota-agent.service ${D}${systemd_system_unitdir}/ivi-ota-agent.service

    if ${@bb.utils.contains('PACKAGECONFIG', 'ros2-coordination', 'true', 'false', d)}; then
        sed -i '/^After=/ s/$/ update-coordinator.service/' \
            ${D}${systemd_system_unitdir}/ivi-ota-agent.service
    fi

    install -d -m 0700 ${D}${sysconfdir}/ivi-ota
    
    install -m 0600 ${OTA_AGENT_PRIVATE_KEY_PATH} ${D}${sysconfdir}/ivi-ota/ivi_priv.pem

    install -m 0600 ${OTA_AGENT_CONF_PATH} ${D}${sysconfdir}/ivi-ota/agent.conf

    # INITIAL_VERSION is GENERATED, not taken from agent.conf.
    #
    # It is the version the agent reports when it has no /data/ota/installed_version
    # to read, so it has to name the version actually baked into THIS image. Left to
    # a hand-edited value in the out-of-tree secret/agent.conf it drifts the first
    # time someone bumps a payload and forgets, and nothing complains until a
    # flashed board either accepts a downgrade or refuses a legitimate update.
    #
    # Any INITIAL_VERSION already in agent.conf is deleted rather than left in
    # place. agent.conf is sourced by sh so the appended one would win regardless,
    # but a file containing two different answers is a trap for whoever reads it
    # on the board next.
    sed -i '/^[[:space:]]*INITIAL_VERSION=/d' ${D}${sysconfdir}/ivi-ota/agent.conf

    # Fail the build rather than ship a floor the agent will reject at runtime:
    # installed_version() validates against ^[0-9]+\.[0-9]+\.[0-9]+$ and falls
    # back to 0.0.0 on anything else, which is the one value this whole mechanism
    # exists to avoid.
    echo "${VPACE_OTA_VERSION}" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' || \
        bbfatal "VPACE_OTA_VERSION is '${VPACE_OTA_VERSION}', not a bare X.Y.Z semver"

    # printf, not echo >>: agent.conf is operator-edited and may not end in a
    # newline, which would glue this onto the last line.
    printf '\n# --- generated by ivi-ota-agent.bb, do not edit on the board ---\n# Fallback for when /data/ota/installed_version is missing. Bump it in\n# meta-vpace/conf/include/vpace-ota-version.inc, which also drives\n# IVI_APP_VERSION and ACKERMANN_VERSION.\nINITIAL_VERSION=%s\n' \
        "${VPACE_OTA_VERSION}" >> ${D}${sysconfdir}/ivi-ota/agent.conf

    # Approval spool. /run is a tmpfs, so systemd-tmpfiles has to recreate it on
    # every boot; the mode on verdicts/ is what lets the unprivileged IVI app
    # answer without being able to read or forge anything.
    install -d ${D}${nonarch_libdir}/tmpfiles.d
    install -m 0644 ${WORKDIR}/ota-approval-tmpfiles.conf \
        ${D}${nonarch_libdir}/tmpfiles.d/ota-approval.conf
}

FILES:${PN} += "${systemd_system_unitdir}/ivi-ota-agent.service \
                ${sysconfdir}/ivi-ota \
                ${nonarch_libdir}/tmpfiles.d"

# The agent keeps its installed-version file at /data/ota/installed_version, NOT
# under /var/lib/ivi-ota with the rest of its state. /var/lib is on the A/B rootfs
# pair that a full .swu replaces wholesale; /data (nvme0n1p15) survives. If it
# ever moves back onto the rootfs, the board forgets what it is running after
# every update -- it reinstalls the campaign it is already on, and the
# ALLOW_DOWNGRADE gate stops rejecting replayed old packages.
#
# /var/lib/ivi-ota stays as the download scratch (StateDirectory= in the unit):
# it holds the encrypted blob and the decrypted .swu at the same time, and that
# is exactly the traffic /data must not absorb.
