# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-vpace"
BBFILE_PATTERN_meta-vpace = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-vpace = "6"

LAYERDEPENDS_meta-vpace = "core"
LAYERSERIES_COMPAT_meta-vpace = "scarthgap"

# pre-accept commercial licenses 
LICENSE_FLAGS_ACCEPTED += " commercial_gstreamer1.0-plugins-ugly "