require conf/distro/tegrademo.conf

DISTRO = "vpace"
DISTRO_NAME = "V-PACE Distribution"
DISTRO_VERSION_BASE = "1.0"
DISTRO_VERSION = "${DISTRO_VERSION_BASE}.0"


# needed to pypass the qa-sanity of the tegrademo that our distro builds upon
INHERIT:remove = "tegra-support-sanity"

DISTRO_FEATURES:append = " wayland"
DISTRO_FEATURES:remove = " x11"
# not needed for now so we remove them
DISTRO_FEATURES:remove = " ptest debuginfod virtualization nfc 3g pcmcia zeroconf nfs "
# since we dont need the virtualization (no docker) 
BBMASK += "docker-moby_%.bbappend"


# Qt6 platform
# QT_QPA_PLATFORM = "wayland"
# QT_QPA_PLATFORMTHEME = "gtk2"