/**
 * @file v_pace_db.c
 *
 * @brief This source file was generated by cantools version 42.0.1 Thu Jun 25 16:16:23 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "v_pace_db.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int v_pace_db_encoder_data_unpack(
    struct v_pace_db_encoder_data_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t left_ticks;
    uint32_t right_ticks;

    if (size < 8u) {
        return (-EINVAL);
    }

    left_ticks = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    left_ticks |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    left_ticks |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    left_ticks |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->left_ticks = (int32_t)left_ticks;
    right_ticks = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    right_ticks |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    right_ticks |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    right_ticks |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    dst_p->right_ticks = (int32_t)right_ticks;

    return (0);
}

int v_pace_db_encoder_data_init(struct v_pace_db_encoder_data_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v_pace_db_encoder_data_t));

    return 0;
}

float v_pace_db_encoder_data_left_ticks_decode(int32_t value)
{
    return ((float)value);
}

bool v_pace_db_encoder_data_left_ticks_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

bool v_pace_db_encoder_data_left_ticks_is_in_phys_range(float value)
{
    return ((value >= -2147483648.0f) && (value <= 2147483647.0f));
}

float v_pace_db_encoder_data_right_ticks_decode(int32_t value)
{
    return ((float)value);
}

bool v_pace_db_encoder_data_right_ticks_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

bool v_pace_db_encoder_data_right_ticks_is_in_phys_range(float value)
{
    return ((value >= -2147483648.0f) && (value <= 2147483647.0f));
}

int v_pace_db_imu_accel_unpack(
    struct v_pace_db_imu_accel_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t accel_x;
    uint16_t accel_y;
    uint16_t accel_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    accel_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    accel_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->accel_x = (int16_t)accel_x;
    accel_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    accel_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->accel_y = (int16_t)accel_y;
    accel_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    accel_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->accel_z = (int16_t)accel_z;
    dst_p->sequence = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->reserved = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int v_pace_db_imu_accel_init(struct v_pace_db_imu_accel_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v_pace_db_imu_accel_t));

    return 0;
}

float v_pace_db_imu_accel_accel_x_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool v_pace_db_imu_accel_accel_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool v_pace_db_imu_accel_accel_x_is_in_phys_range(float value)
{
    return ((value >= -32.768f) && (value <= 32.767f));
}

float v_pace_db_imu_accel_accel_y_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool v_pace_db_imu_accel_accel_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool v_pace_db_imu_accel_accel_y_is_in_phys_range(float value)
{
    return ((value >= -32.768f) && (value <= 32.767f));
}

float v_pace_db_imu_accel_accel_z_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool v_pace_db_imu_accel_accel_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool v_pace_db_imu_accel_accel_z_is_in_phys_range(float value)
{
    return ((value >= -32.768f) && (value <= 32.767f));
}

float v_pace_db_imu_accel_sequence_decode(uint8_t value)
{
    return ((float)value);
}

bool v_pace_db_imu_accel_sequence_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v_pace_db_imu_accel_sequence_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 255.0f));
}

float v_pace_db_imu_accel_reserved_decode(uint8_t value)
{
    return ((float)value);
}

bool v_pace_db_imu_accel_reserved_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v_pace_db_imu_accel_reserved_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 255.0f));
}

int v_pace_db_imu_gyro_flags_unpack(
    struct v_pace_db_imu_gyro_flags_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t gyro_x;
    uint16_t gyro_y;
    uint16_t gyro_z;

    if (size < 8u) {
        return (-EINVAL);
    }

    gyro_x = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    gyro_x |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->gyro_x = (int16_t)gyro_x;
    gyro_y = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    gyro_y |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->gyro_y = (int16_t)gyro_y;
    gyro_z = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    gyro_z |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->gyro_z = (int16_t)gyro_z;
    dst_p->imu_reset = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->sequence = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int v_pace_db_imu_gyro_flags_init(struct v_pace_db_imu_gyro_flags_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v_pace_db_imu_gyro_flags_t));

    return 0;
}

float v_pace_db_imu_gyro_flags_gyro_x_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool v_pace_db_imu_gyro_flags_gyro_x_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool v_pace_db_imu_gyro_flags_gyro_x_is_in_phys_range(float value)
{
    return ((value >= -32.768f) && (value <= 32.767f));
}

float v_pace_db_imu_gyro_flags_gyro_y_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool v_pace_db_imu_gyro_flags_gyro_y_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool v_pace_db_imu_gyro_flags_gyro_y_is_in_phys_range(float value)
{
    return ((value >= -32.768f) && (value <= 32.767f));
}

float v_pace_db_imu_gyro_flags_gyro_z_decode(int16_t value)
{
    return ((float)value * 0.001f);
}

bool v_pace_db_imu_gyro_flags_gyro_z_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool v_pace_db_imu_gyro_flags_gyro_z_is_in_phys_range(float value)
{
    return ((value >= -32.768f) && (value <= 32.767f));
}

float v_pace_db_imu_gyro_flags_imu_reset_decode(uint8_t value)
{
    return ((float)value);
}

bool v_pace_db_imu_gyro_flags_imu_reset_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool v_pace_db_imu_gyro_flags_imu_reset_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 1.0f));
}

float v_pace_db_imu_gyro_flags_sequence_decode(uint8_t value)
{
    return ((float)value);
}

bool v_pace_db_imu_gyro_flags_sequence_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v_pace_db_imu_gyro_flags_sequence_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 255.0f));
}

int v_pace_db_motor_commands_pack(
    uint8_t *dst_p,
    const struct v_pace_db_motor_commands_t *src_p,
    size_t size)
{
    uint32_t left_vel;
    uint32_t right_vel;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    memcpy(&left_vel, &src_p->left_vel, sizeof(left_vel));
    dst_p[0] |= pack_left_shift_u32(left_vel, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(left_vel, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(left_vel, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(left_vel, 24u, 0xffu);
    memcpy(&right_vel, &src_p->right_vel, sizeof(right_vel));
    dst_p[4] |= pack_left_shift_u32(right_vel, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(right_vel, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(right_vel, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(right_vel, 24u, 0xffu);

    return (8);
}

int v_pace_db_motor_commands_init(struct v_pace_db_motor_commands_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v_pace_db_motor_commands_t));

    return 0;
}

float v_pace_db_motor_commands_left_vel_encode(float value)
{
    return (float)(value);
}

bool v_pace_db_motor_commands_left_vel_is_in_range(float value)
{
    return ((value >= -3.4e+38f) && (value <= 3.4e+38f));
}

bool v_pace_db_motor_commands_left_vel_is_in_phys_range(float value)
{
    return ((value >= -3.4e+38f) && (value <= 3.4e+38f));
}

float v_pace_db_motor_commands_right_vel_encode(float value)
{
    return (float)(value);
}

bool v_pace_db_motor_commands_right_vel_is_in_range(float value)
{
    return ((value >= -3.4e+38f) && (value <= 3.4e+38f));
}

bool v_pace_db_motor_commands_right_vel_is_in_phys_range(float value)
{
    return ((value >= -3.4e+38f) && (value <= 3.4e+38f));
}

int v_pace_db_steering_command_pack(
    uint8_t *dst_p,
    const struct v_pace_db_steering_command_t *src_p,
    size_t size)
{
    uint32_t steer_angle;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    memcpy(&steer_angle, &src_p->steer_angle, sizeof(steer_angle));
    dst_p[0] |= pack_left_shift_u32(steer_angle, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(steer_angle, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(steer_angle, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(steer_angle, 24u, 0xffu);

    return (4);
}

int v_pace_db_steering_command_init(struct v_pace_db_steering_command_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v_pace_db_steering_command_t));

    return 0;
}

float v_pace_db_steering_command_steer_angle_encode(float value)
{
    return (float)(value);
}

bool v_pace_db_steering_command_steer_angle_is_in_range(float value)
{
    return ((value >= -3.4e+38f) && (value <= 3.4e+38f));
}

bool v_pace_db_steering_command_steer_angle_is_in_phys_range(float value)
{
    return ((value >= -3.4e+38f) && (value <= 3.4e+38f));
}

int v_pace_db_reset_command_pack(
    uint8_t *dst_p,
    const struct v_pace_db_reset_command_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->reset, 0u, 0xffu);

    return (1);
}

int v_pace_db_reset_command_init(struct v_pace_db_reset_command_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v_pace_db_reset_command_t));

    return 0;
}

uint8_t v_pace_db_reset_command_reset_encode(float value)
{
    return (uint8_t)(value);
}

bool v_pace_db_reset_command_reset_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool v_pace_db_reset_command_reset_is_in_phys_range(float value)
{
    return ((value >= 0.0f) && (value <= 1.0f));
}
